name: Deploy Mode Validation & Inference

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        python-version: [3.8, '3.10']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}-${{ matrix.python-version }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install YOLO package
      run: pip install -e .

    - name: Cache model weights
      id: cache-weights
      uses: actions/cache@v2
      with:
        path: weights
        key: ${{ runner.os }}-weights
        restore-keys: |
          ${{ runner.os }}-weights

    - name: Run Validation
      run: |
        python yolo/lazy.py task=validation dataset=mock
        python yolo/lazy.py task=validation dataset=mock model=v9-s
        python yolo/lazy.py task=validation dataset=mock name=AnyNameYouWant

    - name: Run Inference
      run: |
        python yolo/lazy.py task=inference
        python yolo/lazy.py task=inference model=v7
        python yolo/lazy.py task=inference +quite=True
        python yolo/lazy.py task=inference name=AnyNameYouWant
        python yolo/lazy.py task=inference image_size=\[480,640]
        python yolo/lazy.py task=inference task.nms.min_confidence=0.1
        python yolo/lazy.py task=inference task.fast_inference=deploy
        python yolo/lazy.py task=inference task.data.source=tests/data/images/val
